"""Small, dependency-free Python client for the Palimpsest HTTP API."""

from .client import (
    PalimpsestBinaryResponse,
    PalimpsestClient,
    PalimpsestConfigurationError,
    PalimpsestError,
    PalimpsestHttpError,
    PalimpsestResponse,
    PalimpsestProtocolError,
    PalimpsestTimeoutError,
    PalimpsestTransportError,
    PartialRememberError,
)
from .ingest import (
    IngestReport,
    IngestionError,
    IngestionRunner,
    ProjectIdentity,
    SessionEvent,
    SourceSpec,
    parse_claude_record,
    parse_codex_record,
    parse_hermes_row,
    project_namespace,
    redact_sensitive_text,
)

__all__ = [
    "PalimpsestBinaryResponse",
    "PalimpsestClient",
    "PalimpsestConfigurationError",
    "PalimpsestError",
    "PalimpsestHttpError",
    "PalimpsestResponse",
    "PalimpsestProtocolError",
    "PalimpsestTimeoutError",
    "PalimpsestTransportError",
    "PartialRememberError",
    "IngestReport",
    "IngestionError",
    "IngestionRunner",
    "ProjectIdentity",
    "SessionEvent",
    "SourceSpec",
    "parse_claude_record",
    "parse_codex_record",
    "parse_hermes_row",
    "project_namespace",
    "redact_sensitive_text",
]
